### ISSUE TITLE
Archive this repo?

### ISSUE THREAD

**Issue by mattip** [MacPython/pywavelets-wheels#16]
Can we archive this repo? Many of the multibuild projects under this org have moved to cibuildwheel, and now build via CI jobs on the main repo. Is this true of pywt?

**Comment by rgommers** [comment]
Yes indeed, we can. We use `cibuildwheel` now: https://github.com/PyWavelets/pywt/blob/master/.github/workflows/wheel_tests_and_release.yml

@grlee77 do you see any reason not to archive this repo now?

**Comment by grlee77** [comment]
I agree that we should probably archive it to avoid confusion. I guess just update the README to point to the main repo and then we can set it to archived?

**Comment by mattip** [comment]
OK, I will do that
